export interface CompanyInfo {
  name: string;
  slug: string;
  industry: string;
  headquarters: string;
  commonDisputes: string[];
  regulatoryBodies: string[];
  complaintChannels: string[];
  estimatedResolutionTime: string;
  difficultyLevel: "Easy" | "Medium" | "Hard";
  tips: string[];
}

export const COMPANIES: CompanyInfo[] = [
  // ─── Tech & E-Commerce ────────────────────────────────────────────────────────
  {
    name: "Amazon",
    slug: "amazon",
    industry: "Tech & E-Commerce",
    headquarters: "Seattle, WA",
    commonDisputes: ["subscription-refund", "denied-warranty", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Amazon A-to-Z Guarantee"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Always document order numbers and screenshots of product listings",
      "Use the A-to-Z Guarantee claim process before escalating",
      "Amazon often resolves complaints quickly when an FTC complaint is filed",
      "Keep all chat transcripts with customer service representatives",
    ],
  },
  {
    name: "Apple",
    slug: "apple",
    industry: "Tech & E-Commerce",
    headquarters: "Cupertino, CA",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Apple Support Escalation"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Request a senior advisor when calling Apple Support",
      "Document serial numbers and purchase receipts for warranty claims",
      "Apple has a one-time exception policy for accidental damage — ask about it",
      "File a complaint with your state AG if Apple refuses a valid warranty claim",
    ],
  },
  {
    name: "Google",
    slug: "google",
    industry: "Tech & E-Commerce",
    headquarters: "Mountain View, CA",
    commonDisputes: ["subscription-refund", "data-broker-takedown", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "FCC"],
    complaintChannels: ["BBB", "FTC", "State AG", "Google Support Form"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Google support is notoriously difficult to reach — escalate through social media",
      "File a complaint with the FTC for billing issues with Google Play",
      "For data privacy issues, cite the CCPA or your state privacy law",
      "Document everything — Google rarely provides direct phone support",
    ],
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    industry: "Tech & E-Commerce",
    headquarters: "Redmond, WA",
    commonDisputes: ["subscription-refund", "denied-warranty", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Microsoft Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Use the Microsoft Support virtual agent to create a documented case number",
      "Xbox and Surface warranty claims can be escalated through the Microsoft Store",
      "Request a callback from a supervisor if the first agent cannot help",
      "Keep records of all subscription charges and cancellation confirmations",
    ],
  },
  {
    name: "Meta / Facebook",
    slug: "meta-facebook",
    industry: "Tech & E-Commerce",
    headquarters: "Menlo Park, CA",
    commonDisputes: ["data-broker-takedown", "general-demand-letter", "dmca-takedown"],
    regulatoryBodies: ["FTC", "State Attorney General", "FCC"],
    complaintChannels: ["FTC", "State AG", "Facebook Help Center"],
    estimatedResolutionTime: "4-8 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Meta has no phone support — all complaints must go through online forms",
      "For account issues, file with the State AG office for faster response",
      "CCPA data deletion requests must be honored within 45 days",
      "Document all screenshots of issues before submitting complaints",
    ],
  },
  {
    name: "eBay",
    slug: "ebay",
    industry: "Tech & E-Commerce",
    headquarters: "San Jose, CA",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "subscription-refund"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "eBay Money Back Guarantee"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Use eBay's Money Back Guarantee before filing external complaints",
      "Open a case within 30 days of estimated delivery for best results",
      "eBay tends to side with buyers in disputes — document everything",
      "If the seller is unresponsive, eBay will auto-resolve in your favor after 3 days",
    ],
  },
  {
    name: "Etsy",
    slug: "etsy",
    industry: "Tech & E-Commerce",
    headquarters: "Brooklyn, NY",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "subscription-refund"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Etsy Case System"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Open a case through the Etsy Resolution Center within 100 days of estimated delivery",
      "Always communicate through the Etsy platform for a documented trail",
      "Etsy Purchase Protection covers items not received or not as described",
      "Upload photos to support your case if the item arrived damaged or incorrect",
    ],
  },
  {
    name: "Walmart",
    slug: "walmart",
    industry: "Tech & E-Commerce",
    headquarters: "Bentonville, AR",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Walmart Customer Care"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Walmart has a generous return policy — try in-store returns first",
      "For online orders, use the Walmart app to initiate returns or replacements",
      "Keep receipts and order confirmations as proof of purchase",
      "Marketplace seller disputes can be escalated to Walmart corporate",
    ],
  },
  {
    name: "Best Buy",
    slug: "best-buy",
    industry: "Tech & E-Commerce",
    headquarters: "Richfield, MN",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Best Buy Corporate"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Geek Squad protection plans have specific terms — read them before filing",
      "Best Buy Total Tech members get extended return windows",
      "Escalate to a store manager for in-store disputes before going corporate",
      "Document product defects with photos and video before returning",
    ],
  },
  {
    name: "Samsung",
    slug: "samsung",
    industry: "Tech & E-Commerce",
    headquarters: "Ridgefield Park, NJ",
    commonDisputes: ["denied-warranty", "general-demand-letter", "lemon-law"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Samsung Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Samsung's warranty requires proof of purchase — keep your receipt",
      "Use Samsung Members app to document issues and create service tickets",
      "For repeated appliance issues, cite the Magnuson-Moss Warranty Act",
      "Request an executive escalation if standard support is unhelpful",
    ],
  },
  {
    name: "Sony",
    slug: "sony",
    industry: "Tech & E-Commerce",
    headquarters: "San Mateo, CA",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Sony Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "PlayStation Network refund requests must be made within 14 days of purchase",
      "Sony warranty claims require a case number — call support first",
      "Document any product defects with video for warranty claims",
      "File a BBB complaint if Sony refuses a valid warranty claim",
    ],
  },
  {
    name: "LG",
    slug: "lg",
    industry: "Tech & E-Commerce",
    headquarters: "Englewood Cliffs, NJ",
    commonDisputes: ["denied-warranty", "general-demand-letter", "lemon-law"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "LG Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "LG appliances come with manufacturer warranties — check your terms",
      "Register your product online to streamline the warranty process",
      "For compressor issues on refrigerators, LG often has extended warranty programs",
      "Cite the Magnuson-Moss Warranty Act for repeated defects",
    ],
  },
  {
    name: "Dell",
    slug: "dell",
    industry: "Tech & E-Commerce",
    headquarters: "Round Rock, TX",
    commonDisputes: ["denied-warranty", "general-demand-letter", "subscription-refund"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Dell Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Dell has tiered support — request escalation to ProSupport if available",
      "Keep your service tag number handy for all warranty interactions",
      "Dell Outlet and Refurbished products have different warranty terms",
      "Document all interactions with Dell support including case numbers",
    ],
  },
  {
    name: "HP",
    slug: "hp",
    industry: "Tech & E-Commerce",
    headquarters: "Palo Alto, CA",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "HP Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "HP Instant Ink subscription cancellation disputes are common — document your cancellation",
      "Use the HP Support Assistant to create a case number before calling",
      "HP warranty claims require proof of purchase and product serial number",
      "Escalate to HP Executive Customer Relations for unresolved issues",
    ],
  },
  {
    name: "Lenovo",
    slug: "lenovo",
    industry: "Tech & E-Commerce",
    headquarters: "Morrisville, NC",
    commonDisputes: ["denied-warranty", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Lenovo Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Lenovo warranty claims require your machine type and serial number",
      "Request an accidental damage warranty upgrade when purchasing for protection",
      "Use the Lenovo Vantage app to check warranty status and create tickets",
      "For repeated defects, request a replacement unit rather than another repair",
    ],
  },
  {
    name: "PayPal",
    slug: "paypal",
    industry: "Tech & E-Commerce",
    headquarters: "San Jose, CA",
    commonDisputes: ["chargeback-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["CFPB", "FTC", "State Attorney General"],
    complaintChannels: ["CFPB", "BBB", "FTC", "State AG", "PayPal Resolution Center"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Open a dispute through the PayPal Resolution Center within 180 days",
      "PayPal Purchase Protection covers eligible items not received or not as described",
      "Escalate disputes to a claim if the seller does not respond within 20 days",
      "File a CFPB complaint for account holds or frozen funds issues",
    ],
  },
  {
    name: "Venmo",
    slug: "venmo",
    industry: "Tech & E-Commerce",
    headquarters: "San Jose, CA",
    commonDisputes: ["chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["CFPB", "FTC", "State Attorney General"],
    complaintChannels: ["CFPB", "BBB", "FTC", "State AG", "Venmo Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Venmo Purchase Protection only covers goods and services transactions — not personal payments",
      "Use the 'goods and services' payment type for any purchases to get buyer protection",
      "File a CFPB complaint for unauthorized transactions or account holds",
      "Document all transaction details and communications with the other party",
    ],
  },
  {
    name: "Cash App",
    slug: "cash-app",
    industry: "Tech & E-Commerce",
    headquarters: "San Francisco, CA",
    commonDisputes: ["chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["CFPB", "FTC", "State Attorney General"],
    complaintChannels: ["CFPB", "BBB", "FTC", "State AG", "Cash App Support"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Cash App payments are generally instant and non-reversible — document fraud quickly",
      "Request a refund through the app first, then escalate to Cash App support",
      "File a CFPB complaint for unauthorized transactions",
      "For scam transactions, file a police report and provide it to Cash App",
    ],
  },
  {
    name: "Shopify Sellers",
    slug: "shopify-sellers",
    industry: "Tech & E-Commerce",
    headquarters: "Ottawa, ON (various sellers)",
    commonDisputes: ["chargeback-dispute", "subscription-refund", "denied-warranty", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Shopify Support", "Credit Card Chargeback"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Identify the actual seller — Shopify is just the platform, not the merchant",
      "Use your credit card chargeback rights if the seller is unresponsive",
      "Report fraudulent Shopify stores to Shopify directly at shopify.com/legal/report",
      "Document the store URL, product pages, and all order confirmations",
    ],
  },
  {
    name: "Wish",
    slug: "wish",
    industry: "Tech & E-Commerce",
    headquarters: "San Francisco, CA",
    commonDisputes: ["chargeback-dispute", "denied-warranty", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Wish Customer Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Wish has a refund policy for items not as described — file within 30 days",
      "Take photos of what you received vs. what was advertised",
      "Use credit card chargeback as a last resort if Wish denies your refund",
      "File an FTC complaint if Wish advertised misleading product descriptions",
    ],
  },

  // ─── Telecom & Internet ───────────────────────────────────────────────────────
  {
    name: "AT&T",
    slug: "att",
    industry: "Telecom & Internet",
    headquarters: "Dallas, TX",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC", "AT&T Executive Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "AT&T has an executive escalation team — write to the Office of the President",
      "File an FCC complaint for billing issues — AT&T must respond within 30 days",
      "Keep records of all promotional rate agreements and confirmations",
      "Request an itemized bill to identify unauthorized charges",
    ],
  },
  {
    name: "Verizon",
    slug: "verizon",
    industry: "Telecom & Internet",
    headquarters: "New York, NY",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC", "Verizon Executive Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Verizon must honor advertised promotional rates — keep screenshots",
      "File an FCC complaint for the fastest resolution on billing disputes",
      "Request a supervisor or executive escalation if standard support fails",
      "Check your bill for hidden fees like administrative charges and surcharges",
    ],
  },
  {
    name: "T-Mobile",
    slug: "t-mobile",
    industry: "Telecom & Internet",
    headquarters: "Bellevue, WA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC", "T-Mobile Executive Response"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "T-Mobile has a Team of Experts model — ask for your dedicated team",
      "File a complaint through the T-Mobile app for a documented trail",
      "T-Mobile tends to resolve BBB complaints quickly",
      "Keep screenshots of rate plan confirmations and promotional offers",
    ],
  },
  {
    name: "Comcast / Xfinity",
    slug: "comcast-xfinity",
    industry: "Telecom & Internet",
    headquarters: "Philadelphia, PA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC", "Comcast Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Comcast has a dedicated executive customer relations team — email them directly",
      "FCC complaints are very effective against Comcast and trigger a mandatory response",
      "Request an itemized bill breakdown to dispute hidden fees",
      "Check for early termination fees before cancelling — negotiate a waiver",
    ],
  },
  {
    name: "Spectrum",
    slug: "spectrum",
    industry: "Telecom & Internet",
    headquarters: "Stamford, CT",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC", "Spectrum Executive Office"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Spectrum no longer uses contracts — you should be able to cancel without fees",
      "File an FCC complaint if Spectrum raises your rate without proper notice",
      "Request a speed test if your internet is slower than advertised",
      "Ask for retention department offers before cancelling service",
    ],
  },
  {
    name: "Cox Communications",
    slug: "cox-communications",
    industry: "Telecom & Internet",
    headquarters: "Atlanta, GA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC", "Cox Executive Escalations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Cox data caps can result in surprise overage fees — check your plan limits",
      "File an FCC complaint for billing disputes for the fastest response",
      "Request a service credit for documented outages affecting your area",
      "Keep records of all rate agreements and promotional period end dates",
    ],
  },
  {
    name: "CenturyLink / Lumen",
    slug: "centurylink",
    industry: "Telecom & Internet",
    headquarters: "Monroe, LA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "CenturyLink has faced multiple state AG actions for billing practices — cite them",
      "File an FCC complaint for unauthorized charges or billing errors",
      "Request early termination fee waivers if service was consistently below advertised speeds",
      "Document speed tests over time to prove service deficiency",
    ],
  },
  {
    name: "Frontier Communications",
    slug: "frontier-communications",
    industry: "Telecom & Internet",
    headquarters: "Dallas, TX",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General", "State PUC"],
    complaintChannels: ["FCC", "BBB", "State AG", "State PUC"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Frontier went through bankruptcy — verify your account details and terms",
      "File an FCC complaint for billing disputes — Frontier must respond",
      "Document service outages with timestamps and speed test results",
      "Check if fiber is available in your area — Frontier is upgrading many markets",
    ],
  },
  {
    name: "Cricket Wireless",
    slug: "cricket-wireless",
    industry: "Telecom & Internet",
    headquarters: "Atlanta, GA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "Cricket Support"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Cricket is owned by AT&T — escalate unresolved issues to AT&T corporate",
      "Cricket is prepaid, so billing disputes are usually about unauthorized auto-pay charges",
      "File an FCC complaint for the most effective resolution path",
      "Document all interactions through the Cricket app or website",
    ],
  },
  {
    name: "Boost Mobile",
    slug: "boost-mobile",
    industry: "Telecom & Internet",
    headquarters: "Broomfield, CO",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "Boost Mobile Support"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Boost Mobile is owned by Dish Network — escalate to Dish if needed",
      "As a prepaid carrier, most disputes involve unauthorized charges or service quality",
      "File an FCC complaint for network issues or billing problems",
      "Keep records of all plan changes and confirmations",
    ],
  },
  {
    name: "Mint Mobile",
    slug: "mint-mobile",
    industry: "Telecom & Internet",
    headquarters: "Costa Mesa, CA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "Mint Mobile Support"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Mint Mobile is now owned by T-Mobile — escalate to T-Mobile corporate if needed",
      "Mint sells service in multi-month blocks — refund disputes are common",
      "File an FCC complaint if Mint refuses to process a valid refund",
      "Check coverage maps before purchasing — network gaps are a common complaint",
    ],
  },
  {
    name: "Google Fi",
    slug: "google-fi",
    industry: "Telecom & Internet",
    headquarters: "Mountain View, CA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "Google Fi Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Google Fi support is primarily online — use chat for a documented trail",
      "File an FCC complaint for billing disputes — Google must respond",
      "Google Fi offers bill protection to cap your monthly data charges",
      "Request a case escalation if standard support cannot resolve your issue",
    ],
  },
  {
    name: "Starlink",
    slug: "starlink",
    industry: "Telecom & Internet",
    headquarters: "Hawthorne, CA",
    commonDisputes: ["subscription-refund", "general-demand-letter", "denied-warranty"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "Starlink Support"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Starlink has a 30-day return policy for the hardware kit — act fast",
      "File an FCC complaint for service quality or billing issues",
      "Document speed test results to support your complaint",
      "Starlink support is email-only — keep all correspondence",
    ],
  },
  {
    name: "Dish Network",
    slug: "dish-network",
    industry: "Telecom & Internet",
    headquarters: "Englewood, CO",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "Dish Network Executive Office"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Dish contracts include early termination fees — negotiate a waiver if service was poor",
      "File an FCC complaint for billing disputes or unauthorized charges",
      "Request an itemized bill to identify hidden fees and surcharges",
      "Ask about promotional rate extensions before your contract expires",
    ],
  },
  {
    name: "DirecTV",
    slug: "directv",
    industry: "Telecom & Internet",
    headquarters: "El Segundo, CA",
    commonDisputes: ["telecom-billing-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FCC", "FTC", "State Attorney General"],
    complaintChannels: ["FCC", "BBB", "State AG", "DirecTV Executive Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "DirecTV early termination fees can be substantial — negotiate based on service issues",
      "File an FCC complaint for billing disputes or unauthorized plan changes",
      "Request equipment return shipping labels before cancellation to avoid charges",
      "Document all promotional rate agreements with dates and confirmation numbers",
    ],
  },

  // ─── Insurance ────────────────────────────────────────────────────────────────
  {
    name: "State Farm",
    slug: "state-farm",
    industry: "Insurance",
    headquarters: "Bloomington, IL",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "State Farm Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Always get a second estimate for auto repairs — State Farm's estimate may be low",
      "File a complaint with your State Insurance Commissioner for claim denials",
      "Request the specific policy language justifying any denial",
      "State Farm agents often have more flexibility than the claims department",
    ],
  },
  {
    name: "GEICO",
    slug: "geico",
    industry: "Insurance",
    headquarters: "Chevy Chase, MD",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "GEICO Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "GEICO is direct-to-consumer — there is no local agent to escalate to",
      "Request a claims supervisor if the initial adjuster denies your claim",
      "File a complaint with your State Insurance Commissioner for unfair claim practices",
      "Get independent repair estimates and medical evaluations to counter lowball offers",
    ],
  },
  {
    name: "Progressive",
    slug: "progressive",
    industry: "Insurance",
    headquarters: "Mayfield Village, OH",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "Progressive Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Progressive often uses their own shops for estimates — get an independent estimate too",
      "File a complaint with the State Insurance Commissioner if your claim is unfairly denied",
      "Request a detailed written explanation of any coverage denial",
      "Progressive's Snapshot program data can affect claims — know your rights",
    ],
  },
  {
    name: "Allstate",
    slug: "allstate",
    industry: "Insurance",
    headquarters: "Northbrook, IL",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "Allstate Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Allstate has faced multiple lawsuits for low-balling claims — document everything",
      "Request the policy language that Allstate is citing in any denial",
      "File a complaint with your State Insurance Commissioner for bad faith practices",
      "Get independent appraisals for both vehicle damage and medical expenses",
    ],
  },
  {
    name: "Liberty Mutual",
    slug: "liberty-mutual",
    industry: "Insurance",
    headquarters: "Boston, MA",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "Liberty Mutual Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Liberty Mutual's claims process can be slow — set deadlines in your demand letter",
      "Request a copy of your complete policy file including endorsements",
      "File a State Insurance Commissioner complaint for delayed or denied claims",
      "Document all phone calls with dates, names, and summaries",
    ],
  },
  {
    name: "USAA",
    slug: "usaa",
    industry: "Insurance",
    headquarters: "San Antonio, TX",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "USAA Member Advocacy"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Easy",
    tips: [
      "USAA generally has high satisfaction ratings — ask for a supervisor escalation",
      "Use the USAA Member Advocacy team for unresolved claims disputes",
      "USAA members can request arbitration for disputed claim amounts",
      "Document all interactions through the USAA app for a clear trail",
    ],
  },
  {
    name: "Farmers Insurance",
    slug: "farmers-insurance",
    industry: "Insurance",
    headquarters: "Woodland Hills, CA",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "Farmers Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Farmers agents may help advocate on your behalf — contact your local agent",
      "Request a written explanation of any claim denial with specific policy references",
      "File a State Insurance Commissioner complaint for unfair practices",
      "Get independent estimates for property and vehicle damage claims",
    ],
  },
  {
    name: "Nationwide",
    slug: "nationwide",
    industry: "Insurance",
    headquarters: "Columbus, OH",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "Nationwide Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Nationwide has a multi-step appeals process — exhaust it before filing external complaints",
      "Request the claims adjuster's written report and evaluation",
      "File a State Insurance Commissioner complaint for delayed claim payments",
      "Contact your Nationwide agent to advocate on your behalf with claims",
    ],
  },
  {
    name: "Travelers",
    slug: "travelers",
    industry: "Insurance",
    headquarters: "New York, NY",
    commonDisputes: ["insurance-denial", "car-accident-demand", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "Travelers Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Travelers is one of the largest commercial insurers — know your policy limits",
      "Request a detailed claim evaluation report from your adjuster",
      "File a State Insurance Commissioner complaint for unfair claim practices",
      "Get multiple contractor estimates for property damage claims",
    ],
  },
  {
    name: "MetLife",
    slug: "metlife",
    industry: "Insurance",
    headquarters: "New York, NY",
    commonDisputes: ["insurance-denial", "medical-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "NAIC", "DOL"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "MetLife Claims"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "MetLife handles many employer-sponsored benefits — check if ERISA applies to your plan",
      "Request the Summary Plan Description for employer-provided coverage",
      "File a complaint with the Department of Labor for ERISA plan disputes",
      "MetLife dental and vision denials can often be overturned with proper documentation",
    ],
  },
  {
    name: "Aetna",
    slug: "aetna",
    industry: "Insurance",
    headquarters: "Hartford, CT",
    commonDisputes: ["medical-denial", "insurance-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "CMS", "DOL"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "CMS", "Aetna Appeals"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Aetna is now owned by CVS Health — escalate to CVS Health corporate if needed",
      "Request a peer-to-peer review between your doctor and Aetna's medical director",
      "File a complaint with CMS for Medicare Advantage plan disputes",
      "Cite specific clinical guidelines that support your treatment in the appeal",
    ],
  },
  {
    name: "Cigna",
    slug: "cigna",
    industry: "Insurance",
    headquarters: "Bloomfield, CT",
    commonDisputes: ["medical-denial", "insurance-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "CMS", "DOL"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "CMS", "Cigna Appeals"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Cigna has a dedicated appeals team — follow their internal process first",
      "Request an external review if Cigna denies your internal appeal",
      "Your doctor can request a peer-to-peer review with Cigna's medical director",
      "File a State Insurance Commissioner complaint for repeated claim denials",
    ],
  },
  {
    name: "UnitedHealthcare",
    slug: "unitedhealthcare",
    industry: "Insurance",
    headquarters: "Minnetonka, MN",
    commonDisputes: ["medical-denial", "insurance-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "CMS", "DOL"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "CMS", "UHC Appeals"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "UnitedHealthcare is the largest insurer — their appeals process is multi-layered",
      "Request the specific clinical criteria they used to deny your claim",
      "File a complaint with CMS for Medicare or Medicaid managed care disputes",
      "Have your doctor submit a letter of medical necessity with the appeal",
    ],
  },
  {
    name: "Blue Cross Blue Shield",
    slug: "blue-cross-blue-shield",
    industry: "Insurance",
    headquarters: "Chicago, IL (varies by state)",
    commonDisputes: ["medical-denial", "insurance-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "CMS"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "CMS", "BCBS Appeals"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "BCBS is a federation — your specific plan is run by your state's BCBS company",
      "Contact your state's BCBS company directly for appeals, not the national organization",
      "Request an external independent review after exhausting internal appeals",
      "File a complaint with your State Insurance Commissioner for claim denials",
    ],
  },
  {
    name: "Kaiser Permanente",
    slug: "kaiser-permanente",
    industry: "Insurance",
    headquarters: "Oakland, CA",
    commonDisputes: ["medical-denial", "insurance-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "CMS", "DMHC"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "DMHC", "Kaiser Member Services"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Kaiser is both insurer and provider — appeal through their internal process first",
      "In California, file with the DMHC (Dept. of Managed Health Care) for fastest results",
      "Request a peer-to-peer review between your doctor and Kaiser's reviewer",
      "Kaiser has mandatory arbitration — know your rights under the arbitration clause",
    ],
  },
  {
    name: "Humana",
    slug: "humana",
    industry: "Insurance",
    headquarters: "Louisville, KY",
    commonDisputes: ["medical-denial", "insurance-denial", "general-demand-letter"],
    regulatoryBodies: ["State Insurance Commissioner", "State Attorney General", "CMS"],
    complaintChannels: ["State Insurance Commissioner", "BBB", "State AG", "CMS", "Humana Appeals"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Humana is a major Medicare Advantage provider — CMS complaints are very effective",
      "Request a coverage determination review for Medicare plan disputes",
      "File a complaint with CMS if Humana does not respond to your appeal in time",
      "Have your provider submit supporting documentation with your appeal",
    ],
  },

  // ─── Banking & Finance ────────────────────────────────────────────────────────
  {
    name: "Wells Fargo",
    slug: "wells-fargo",
    industry: "Banking & Finance",
    headquarters: "San Francisco, CA",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "Wells Fargo Executive Office"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Wells Fargo has faced multiple consent orders — cite regulatory history if relevant",
      "File a CFPB complaint for the fastest response on consumer banking issues",
      "Request a written explanation of any account action or fee",
      "Visit a branch and ask for the branch manager for in-person resolution",
    ],
  },
  {
    name: "Chase",
    slug: "chase",
    industry: "Banking & Finance",
    headquarters: "New York, NY",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "Chase Executive Office"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Chase has a dedicated Executive Office that handles escalated complaints",
      "File a CFPB complaint for billing disputes, unauthorized charges, or account issues",
      "Chase credit card disputes must be filed within 60 days of the statement date",
      "Request a chargeback reversal in writing if the initial dispute is denied",
    ],
  },
  {
    name: "Bank of America",
    slug: "bank-of-america",
    industry: "Banking & Finance",
    headquarters: "Charlotte, NC",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "Bank of America Client Care"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "File a CFPB complaint for the fastest resolution on banking issues",
      "Bank of America has a Client Care team for escalated disputes",
      "Request written documentation of any account fees or restrictions",
      "Visit a financial center for in-person dispute resolution",
    ],
  },
  {
    name: "Capital One",
    slug: "capital-one",
    industry: "Banking & Finance",
    headquarters: "McLean, VA",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "Capital One Executive Office"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Capital One has an Executive Office for escalated consumer complaints",
      "File a CFPB complaint for credit card or banking disputes",
      "Capital One credit card disputes can be filed through their app or website",
      "Request a detailed explanation of any credit limit decrease or account closure",
    ],
  },
  {
    name: "Citibank",
    slug: "citibank",
    industry: "Banking & Finance",
    headquarters: "New York, NY",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "Citi Executive Response"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Citibank has an Executive Response team for escalated issues",
      "File a CFPB complaint for credit card or banking disputes",
      "Request a fee waiver in writing — Citi will often reverse fees for good customers",
      "Citi credit card disputes must be filed within 60 days of the statement",
    ],
  },
  {
    name: "US Bank",
    slug: "us-bank",
    industry: "Banking & Finance",
    headquarters: "Minneapolis, MN",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "US Bank Customer Advocacy"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "US Bank has a Customer Advocacy team for unresolved complaints",
      "File a CFPB complaint for account issues or disputed charges",
      "Visit a local branch for in-person dispute resolution",
      "Request a written explanation of any account restrictions or closures",
    ],
  },
  {
    name: "TD Bank",
    slug: "td-bank",
    industry: "Banking & Finance",
    headquarters: "Cherry Hill, NJ",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "TD Bank Customer Care"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "TD Bank has extended store hours — visit in person for faster resolution",
      "File a CFPB complaint for banking disputes or unauthorized charges",
      "TD Bank has faced regulatory actions — cite specific violations if relevant",
      "Request a fee reversal in writing for the best documentation trail",
    ],
  },
  {
    name: "PNC Bank",
    slug: "pnc-bank",
    industry: "Banking & Finance",
    headquarters: "Pittsburgh, PA",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "PNC Customer Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "PNC has a Customer Relations team for escalated complaints",
      "File a CFPB complaint for account issues or disputed charges",
      "Visit a PNC branch for in-person dispute resolution",
      "Request written documentation of all fees and account changes",
    ],
  },
  {
    name: "Discover",
    slug: "discover",
    industry: "Banking & Finance",
    headquarters: "Riverwoods, IL",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General", "FDIC"],
    complaintChannels: ["CFPB", "OCC", "BBB", "State AG", "Discover Executive Office"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Discover has consistently high customer satisfaction — escalation usually works",
      "Discover disputes can be filed by phone with US-based customer service",
      "Discover does not charge foreign transaction fees — dispute any such charges",
      "File a CFPB complaint for persistent billing or credit reporting issues",
    ],
  },
  {
    name: "American Express",
    slug: "american-express",
    industry: "Banking & Finance",
    headquarters: "New York, NY",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "credit-report"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General"],
    complaintChannels: ["CFPB", "BBB", "State AG", "Amex Executive Office"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Amex has strong buyer protection — dispute charges through their app or website",
      "Amex tends to side with cardholders in disputes — document your case well",
      "For membership fee disputes, call retention and ask about downgrade options",
      "Amex chargeback rights extend up to 120 days for some purchase types",
    ],
  },
  {
    name: "Synchrony Financial",
    slug: "synchrony-financial",
    industry: "Banking & Finance",
    headquarters: "Stamford, CT",
    commonDisputes: ["credit-report", "chargeback-dispute", "general-demand-letter", "debt-validation"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General"],
    complaintChannels: ["CFPB", "BBB", "State AG", "Synchrony Customer Service"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Synchrony issues store credit cards for many retailers — identify the specific account",
      "File a CFPB complaint for promotional financing disputes or deferred interest charges",
      "Request a detailed statement showing how interest was calculated",
      "Synchrony deferred interest promotions charge ALL accrued interest if not paid in full — dispute if not disclosed",
    ],
  },
  {
    name: "Credit One Bank",
    slug: "credit-one-bank",
    industry: "Banking & Finance",
    headquarters: "Las Vegas, NV",
    commonDisputes: ["credit-report", "chargeback-dispute", "general-demand-letter", "subscription-refund"],
    regulatoryBodies: ["CFPB", "OCC", "State Attorney General"],
    complaintChannels: ["CFPB", "BBB", "State AG", "Credit One Customer Service"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Credit One is known for high fees — review your card terms carefully",
      "File a CFPB complaint for unauthorized fee charges or billing disputes",
      "Request a complete fee schedule and compare to your card agreement",
      "Document all attempts to cancel or close your account",
    ],
  },
  {
    name: "Equifax",
    slug: "equifax",
    industry: "Banking & Finance",
    headquarters: "Atlanta, GA",
    commonDisputes: ["credit-report", "data-broker-takedown", "general-demand-letter"],
    regulatoryBodies: ["CFPB", "FTC", "State Attorney General"],
    complaintChannels: ["CFPB", "FTC", "State AG", "Equifax Dispute Center"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Equifax must investigate disputes within 30 days under the FCRA",
      "File disputes through their online portal and follow up with a written letter",
      "Cite FCRA Section 611 in your dispute letter for maximum impact",
      "File a CFPB complaint if Equifax fails to investigate or respond in time",
    ],
  },
  {
    name: "Experian",
    slug: "experian",
    industry: "Banking & Finance",
    headquarters: "Costa Mesa, CA",
    commonDisputes: ["credit-report", "data-broker-takedown", "general-demand-letter"],
    regulatoryBodies: ["CFPB", "FTC", "State Attorney General"],
    complaintChannels: ["CFPB", "FTC", "State AG", "Experian Dispute Center"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Experian must investigate disputes within 30 days under the FCRA",
      "File disputes online and send a certified follow-up letter for documentation",
      "Request the method of verification if Experian claims an item is accurate",
      "File a CFPB complaint for non-responsive or incomplete investigations",
    ],
  },
  {
    name: "TransUnion",
    slug: "transunion",
    industry: "Banking & Finance",
    headquarters: "Chicago, IL",
    commonDisputes: ["credit-report", "data-broker-takedown", "general-demand-letter"],
    regulatoryBodies: ["CFPB", "FTC", "State Attorney General"],
    complaintChannels: ["CFPB", "FTC", "State AG", "TransUnion Dispute Center"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "TransUnion must investigate disputes within 30 days under the FCRA",
      "Submit disputes online and follow up with certified mail for documentation",
      "Request a free copy of your report after any dispute investigation",
      "File a CFPB complaint if TransUnion does not properly investigate your dispute",
    ],
  },

  // ─── Airlines & Travel ────────────────────────────────────────────────────────
  {
    name: "Delta Air Lines",
    slug: "delta-air-lines",
    industry: "Airlines & Travel",
    headquarters: "Atlanta, GA",
    commonDisputes: ["subscription-refund", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "Delta Customer Care"],
    estimatedResolutionTime: "2-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "File a DOT complaint for flight cancellations, delays, or lost baggage — airlines must respond",
      "Delta is required to refund you for cancelled flights under DOT rules",
      "Keep boarding passes and baggage claim tickets for all lost luggage claims",
      "Request SkyMiles compensation for delayed or disrupted flights",
    ],
  },
  {
    name: "United Airlines",
    slug: "united-airlines",
    industry: "Airlines & Travel",
    headquarters: "Chicago, IL",
    commonDisputes: ["subscription-refund", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "United Customer Care"],
    estimatedResolutionTime: "2-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "File a DOT complaint for flight-related issues — United must respond within 30 days",
      "United must compensate for involuntary denied boarding under DOT rules",
      "Keep all receipts for expenses caused by flight disruptions",
      "Request a travel certificate if United delays your flight significantly",
    ],
  },
  {
    name: "American Airlines",
    slug: "american-airlines",
    industry: "Airlines & Travel",
    headquarters: "Fort Worth, TX",
    commonDisputes: ["subscription-refund", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "American Airlines Customer Relations"],
    estimatedResolutionTime: "2-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "File a DOT complaint for cancelled flights, lost bags, or denied boarding",
      "American Airlines must refund cancelled flights — do not accept vouchers if you want cash",
      "Keep documentation of all expenses incurred due to flight disruptions",
      "AAdvantage mile disputes should be filed through the loyalty program",
    ],
  },
  {
    name: "Southwest Airlines",
    slug: "southwest-airlines",
    industry: "Airlines & Travel",
    headquarters: "Dallas, TX",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "Southwest Customer Relations"],
    estimatedResolutionTime: "1-4 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Southwest has no change fees — flexible rebooking is standard",
      "File a DOT complaint for significant flight disruptions",
      "Southwest travel funds expire after one year — request an extension if needed",
      "Request Rapid Rewards points compensation for disrupted flights",
    ],
  },
  {
    name: "JetBlue",
    slug: "jetblue",
    industry: "Airlines & Travel",
    headquarters: "Long Island City, NY",
    commonDisputes: ["subscription-refund", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "JetBlue Customer Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Easy",
    tips: [
      "JetBlue's Customer Bill of Rights guarantees compensation for certain delays",
      "File a DOT complaint for cancelled flights or denied boarding",
      "Keep all receipts for hotel and meal expenses due to flight disruptions",
      "JetBlue offers travel credits for delays — push for cash refunds when eligible",
    ],
  },
  {
    name: "Spirit Airlines",
    slug: "spirit-airlines",
    industry: "Airlines & Travel",
    headquarters: "Dania Beach, FL",
    commonDisputes: ["subscription-refund", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "Spirit Guest Services"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Spirit charges for everything — read the fee schedule before booking",
      "File a DOT complaint for cancelled flights — Spirit must refund under federal rules",
      "Spirit's customer service can be difficult to reach — use email for documentation",
      "File a credit card chargeback if Spirit refuses a valid refund request",
    ],
  },
  {
    name: "Frontier Airlines",
    slug: "frontier-airlines",
    industry: "Airlines & Travel",
    headquarters: "Denver, CO",
    commonDisputes: ["subscription-refund", "general-demand-letter", "chargeback-dispute"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "Frontier Customer Relations"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Frontier is an ultra-low-cost carrier — hidden fees are common, review all charges",
      "File a DOT complaint for flight cancellations and refund refusals",
      "Frontier charges for phone support — use their website or app for free",
      "Keep screenshots of fare breakdowns and add-on charges for disputes",
    ],
  },
  {
    name: "Alaska Airlines",
    slug: "alaska-airlines",
    industry: "Airlines & Travel",
    headquarters: "Seattle, WA",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["DOT", "FAA", "State Attorney General"],
    complaintChannels: ["DOT Air Travel Complaints", "BBB", "State AG", "Alaska Airlines Customer Care"],
    estimatedResolutionTime: "1-4 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Alaska Airlines has strong customer satisfaction ratings — escalation usually works",
      "File a DOT complaint for flight cancellations or lost baggage",
      "Alaska guarantees a 20-minute baggage delivery or provides miles compensation",
      "Request Mileage Plan miles as compensation for service disruptions",
    ],
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    industry: "Airlines & Travel",
    headquarters: "San Francisco, CA",
    commonDisputes: ["airbnb-host-dispute", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "Local Consumer Protection"],
    complaintChannels: ["BBB", "FTC", "State AG", "Airbnb Resolution Center"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Report issues within 72 hours of check-in for the best chance at a resolution",
      "Take photos and video of any problems immediately upon arrival",
      "Use the Airbnb Resolution Center for documented communication",
      "File a credit card chargeback if Airbnb denies a valid complaint",
    ],
  },
  {
    name: "Booking.com",
    slug: "booking-com",
    industry: "Airlines & Travel",
    headquarters: "Amsterdam, Netherlands (US: New York, NY)",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General"],
    complaintChannels: ["BBB", "FTC", "State AG", "Booking.com Customer Service"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Document all issues with photos immediately upon arrival at the property",
      "Contact Booking.com before checking out for the best chance of a refund",
      "Request a free cancellation if the property does not match the listing",
      "File a credit card chargeback for non-refundable bookings with major issues",
    ],
  },
  {
    name: "Expedia",
    slug: "expedia",
    industry: "Airlines & Travel",
    headquarters: "Seattle, WA",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General"],
    complaintChannels: ["BBB", "FTC", "State AG", "Expedia Customer Service"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Expedia refund policies depend on the hotel or airline — check your booking terms",
      "Request a supervisor if the first agent cannot process your refund",
      "File a DOT complaint for flight-related issues booked through Expedia",
      "Document all booking confirmations and cancellation attempts",
    ],
  },
  {
    name: "VRBO",
    slug: "vrbo",
    industry: "Airlines & Travel",
    headquarters: "Austin, TX",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General"],
    complaintChannels: ["BBB", "FTC", "State AG", "VRBO Customer Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "VRBO's Book with Confidence Guarantee covers listing accuracy issues",
      "Report problems within 24 hours of check-in for the best resolution",
      "Take photos and video of any property issues immediately upon arrival",
      "File a credit card chargeback if VRBO denies a valid complaint",
    ],
  },

  // ─── Auto ─────────────────────────────────────────────────────────────────────
  {
    name: "Tesla",
    slug: "tesla",
    industry: "Auto",
    headquarters: "Austin, TX",
    commonDisputes: ["lemon-law", "denied-warranty", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "State DMV"],
    complaintChannels: ["NHTSA", "BBB", "State AG", "Tesla Support"],
    estimatedResolutionTime: "4-8 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Tesla has no franchise dealers — all warranty claims go through Tesla directly",
      "File a NHTSA complaint for safety defects to trigger a potential recall",
      "Document all software update issues with screenshots and timestamps",
      "Tesla's mandatory arbitration clause may limit your options — review your purchase agreement",
    ],
  },
  {
    name: "Ford",
    slug: "ford",
    industry: "Auto",
    headquarters: "Dearborn, MI",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "Ford Customer Relationship Center"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Ford's Customer Relationship Center can authorize goodwill repairs after warranty expiration",
      "File a NHTSA complaint for safety-related defects",
      "Use the BBB Auto Line for arbitration — Ford participates in the program",
      "Keep all service records and repair orders as evidence of repeated defects",
    ],
  },
  {
    name: "GM / Chevrolet",
    slug: "gm-chevrolet",
    industry: "Auto",
    headquarters: "Detroit, MI",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "GM Customer Assistance"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "GM participates in BBB Auto Line arbitration — use it for lemon law disputes",
      "File a NHTSA complaint for safety defects to build a case for a recall",
      "GM's Customer Assistance center can authorize goodwill warranty extensions",
      "Document every dealer visit with repair orders and written descriptions of the problem",
    ],
  },
  {
    name: "Toyota",
    slug: "toyota",
    industry: "Auto",
    headquarters: "Plano, TX",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "Toyota Customer Experience Center"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Toyota has a strong warranty reputation — escalate to the Customer Experience Center",
      "File a NHTSA complaint for any safety-related defects",
      "Toyota participates in BBB Auto Line arbitration for warranty disputes",
      "Keep all maintenance records to prove you followed the recommended service schedule",
    ],
  },
  {
    name: "Honda",
    slug: "honda",
    industry: "Auto",
    headquarters: "Torrance, CA",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "Honda Customer Relations"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Honda has a dedicated Customer Relations team for warranty escalations",
      "File a NHTSA complaint for safety-related issues",
      "Honda participates in BBB Auto Line arbitration",
      "Keep all service records — Honda may deny warranty if maintenance was skipped",
    ],
  },
  {
    name: "Nissan",
    slug: "nissan",
    industry: "Auto",
    headquarters: "Franklin, TN",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "Nissan Consumer Affairs"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Nissan has faced class actions for CVT transmission issues — check if your model is affected",
      "File a NHTSA complaint for transmission, engine, or safety defects",
      "Nissan's Consumer Affairs department can authorize goodwill warranty repairs",
      "Document every symptom with video recordings for warranty claims",
    ],
  },
  {
    name: "Hyundai / Kia",
    slug: "hyundai-kia",
    industry: "Auto",
    headquarters: "Fountain Valley, CA / Irvine, CA",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "Hyundai/Kia Customer Care"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Hyundai and Kia have extended engine warranties for certain models due to recalls — check eligibility",
      "File a NHTSA complaint for engine, fire risk, or safety defects",
      "Both brands participate in BBB Auto Line arbitration",
      "Hyundai's 10-year/100K powertrain warranty is only for the original owner — verify transfer terms",
    ],
  },
  {
    name: "BMW",
    slug: "bmw",
    industry: "Auto",
    headquarters: "Woodcliff Lake, NJ",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "BMW Customer Relations"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "BMW warranty repairs must be performed at authorized dealers — document all visits",
      "File a NHTSA complaint for recurring safety-related defects",
      "BMW participates in BBB Auto Line arbitration for lemon law claims",
      "Request a loaner vehicle during extended warranty repairs — it is standard BMW policy",
    ],
  },
  {
    name: "Mercedes-Benz",
    slug: "mercedes-benz",
    industry: "Auto",
    headquarters: "Atlanta, GA",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["NHTSA", "State Attorney General", "BBB Auto Line"],
    complaintChannels: ["NHTSA", "BBB Auto Line", "State AG", "Mercedes-Benz Customer Assistance"],
    estimatedResolutionTime: "3-6 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Mercedes-Benz has a dedicated Customer Assistance Center for warranty escalations",
      "File a NHTSA complaint for safety-related defects",
      "Mercedes participates in BBB Auto Line arbitration",
      "Document all service visits and request copies of dealer repair orders",
    ],
  },
  {
    name: "CarMax",
    slug: "carmax",
    industry: "Auto",
    headquarters: "Richmond, VA",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "CarMax Customer Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "CarMax has a 30-day/1,500-mile return policy — act within this window",
      "CarMax MaxCare warranty has specific terms — read your contract carefully",
      "File a complaint with your State AG for undisclosed vehicle defects",
      "Get an independent pre-purchase inspection to document any issues",
    ],
  },
  {
    name: "Carvana",
    slug: "carvana",
    industry: "Auto",
    headquarters: "Tempe, AZ",
    commonDisputes: ["lemon-law", "denied-warranty", "auto-repair-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "State DMV"],
    complaintChannels: ["BBB", "FTC", "State AG", "Carvana Customer Advocate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Carvana has a 7-day return policy — return the vehicle within this window if issues arise",
      "Carvana has faced regulatory actions in multiple states for title and registration issues",
      "Document all vehicle defects with photos and video upon delivery",
      "File a State AG complaint if Carvana fails to provide title or registration on time",
    ],
  },
  {
    name: "AutoNation",
    slug: "autonation",
    industry: "Auto",
    headquarters: "Fort Lauderdale, FL",
    commonDisputes: ["auto-repair-dispute", "denied-warranty", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "AutoNation Guest Experience"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "AutoNation is the largest auto dealer group in the US — escalate to corporate for unresolved issues",
      "Request detailed repair invoices and compare with independent estimates",
      "File a State AG complaint for deceptive sales practices or undisclosed fees",
      "AutoNation has a guest experience team that handles escalated complaints",
    ],
  },

  // ─── Retail & Food ────────────────────────────────────────────────────────────
  {
    name: "Target",
    slug: "target",
    industry: "Retail & Food",
    headquarters: "Minneapolis, MN",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Target Guest Relations"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Target has a generous return policy — most items can be returned within 90 days",
      "RedCard holders get an extended 120-day return window",
      "Contact Target Guest Relations for unresolved in-store disputes",
      "Keep receipts or use the Target app for receipt-free returns on linked purchases",
    ],
  },
  {
    name: "Costco",
    slug: "costco",
    industry: "Retail & Food",
    headquarters: "Issaquah, WA",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Costco Member Services"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Costco has one of the most generous return policies in retail — nearly everything can be returned anytime",
      "Electronics have a 90-day return window at Costco",
      "Contact Costco Member Services for membership-related disputes",
      "Costco's Concierge Services handles technical support for electronics purchases",
    ],
  },
  {
    name: "Home Depot",
    slug: "home-depot",
    industry: "Retail & Food",
    headquarters: "Atlanta, GA",
    commonDisputes: ["denied-warranty", "general-demand-letter", "auto-repair-dispute"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Home Depot Customer Care"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Home Depot has a 90-day return policy for most items",
      "Pro Xtra members may have different return terms — check your account",
      "For installation disputes, contact the Home Depot Installation team directly",
      "File a complaint with your State AG for contractor or installation issues",
    ],
  },
  {
    name: "Lowe's",
    slug: "lowes",
    industry: "Retail & Food",
    headquarters: "Mooresville, NC",
    commonDisputes: ["denied-warranty", "general-demand-letter", "auto-repair-dispute"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Lowe's Customer Care"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Lowe's has a 90-day return policy with receipt for most items",
      "Lowe's Protection Plans have specific terms — read before purchasing",
      "For installation disputes, escalate to the store manager first",
      "File a complaint with your State AG for contractor or installation quality issues",
    ],
  },
  {
    name: "Macy's",
    slug: "macys",
    industry: "Retail & Food",
    headquarters: "New York, NY",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Macy's Customer Service"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Macy's has a 90-day return policy for most items with receipt",
      "Star Rewards and credit card disputes should go through Citibank (the card issuer)",
      "Contact Macy's customer service for online order issues",
      "File a BBB complaint if Macy's does not resolve your issue within a reasonable time",
    ],
  },
  {
    name: "Nordstrom",
    slug: "nordstrom",
    industry: "Retail & Food",
    headquarters: "Seattle, WA",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Nordstrom Customer Service"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Nordstrom has a very flexible return policy with no strict time limit",
      "Nordstrom Rack has a 45-day return policy — different from main Nordstrom stores",
      "Contact Nordstrom customer service for online order disputes",
      "Nordstrom is generally easy to work with — escalate to a store manager for in-person issues",
    ],
  },
  {
    name: "Nike",
    slug: "nike",
    industry: "Retail & Food",
    headquarters: "Beaverton, OR",
    commonDisputes: ["denied-warranty", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Nike Consumer Services"],
    estimatedResolutionTime: "1-3 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Nike has a 60-day return policy, even for worn items",
      "Nike Members get free returns and extended trial periods",
      "For defective products, Nike may offer a replacement or refund beyond the return window",
      "Contact Nike Consumer Services through chat for the fastest response",
    ],
  },
  {
    name: "Starbucks",
    slug: "starbucks",
    industry: "Retail & Food",
    headquarters: "Seattle, WA",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Starbucks Customer Service"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Starbucks Rewards disputes should be filed through the app or website",
      "For mobile order issues, contact the specific store first",
      "Starbucks gift card balance disputes can be escalated to customer service",
      "Most in-store issues are resolved immediately by the store manager",
    ],
  },
  {
    name: "DoorDash",
    slug: "doordash",
    industry: "Retail & Food",
    headquarters: "San Francisco, CA",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "DoorDash Support"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Report missing or incorrect items through the DoorDash app within 24 hours",
      "DoorDash DashPass subscription can be cancelled anytime — document your cancellation",
      "Take photos of any food quality or missing item issues immediately",
      "File a credit card chargeback if DoorDash denies a valid refund",
    ],
  },
  {
    name: "Uber Eats",
    slug: "uber-eats",
    industry: "Retail & Food",
    headquarters: "San Francisco, CA",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Uber Eats Support"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Report order issues through the Uber Eats app for the fastest refund",
      "Uber One subscription disputes should be filed through the app settings",
      "Take photos of any food issues immediately for your refund claim",
      "File a credit card chargeback if Uber Eats refuses a valid refund",
    ],
  },
  {
    name: "Grubhub",
    slug: "grubhub",
    industry: "Retail & Food",
    headquarters: "Chicago, IL",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Grubhub Support"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Report missing or incorrect items through the Grubhub app within a few hours",
      "Grubhub+ subscription can be cancelled anytime — document your cancellation",
      "Take photos of food quality issues for refund documentation",
      "File a credit card chargeback if Grubhub denies a valid refund",
    ],
  },
  {
    name: "Instacart",
    slug: "instacart",
    industry: "Retail & Food",
    headquarters: "San Francisco, CA",
    commonDisputes: ["subscription-refund", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Instacart Support"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Report missing or wrong items through the Instacart app within 24 hours",
      "Instacart+ subscription can be cancelled anytime — keep cancellation confirmation",
      "Take photos of damaged or incorrect grocery items immediately",
      "Instacart credits typically process faster than full refunds",
    ],
  },
  {
    name: "Chipotle",
    slug: "chipotle",
    industry: "Retail & Food",
    headquarters: "Newport Beach, CA",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB", "FDA"],
    complaintChannels: ["BBB", "FTC", "State AG", "Chipotle Customer Service"],
    estimatedResolutionTime: "1-2 weeks",
    difficultyLevel: "Easy",
    tips: [
      "Report food quality issues directly to the restaurant and through the app",
      "For food safety concerns, also file a report with your local health department",
      "Chipotle Rewards disputes can be resolved through customer service",
      "Keep receipts and take photos of any issues with your order",
    ],
  },

  // ─── Fitness & Services ───────────────────────────────────────────────────────
  {
    name: "Planet Fitness",
    slug: "planet-fitness",
    industry: "Fitness & Services",
    headquarters: "Hampton, NH",
    commonDisputes: ["gym-cancellation", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Planet Fitness Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Planet Fitness requires cancellation in person or by certified mail — plan accordingly",
      "Annual fees are charged regardless of usage — dispute if not disclosed at sign-up",
      "Send cancellation by certified mail with return receipt for proof",
      "File a State AG complaint if they continue charging after valid cancellation",
    ],
  },
  {
    name: "LA Fitness",
    slug: "la-fitness",
    industry: "Fitness & Services",
    headquarters: "Irvine, CA",
    commonDisputes: ["gym-cancellation", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "LA Fitness Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "LA Fitness requires written cancellation — send via certified mail",
      "Check your state's gym membership cancellation laws — many require refund rights",
      "LA Fitness has faced class actions for billing after cancellation — document everything",
      "File a State AG complaint for persistent billing after valid cancellation",
    ],
  },
  {
    name: "Anytime Fitness",
    slug: "anytime-fitness",
    industry: "Fitness & Services",
    headquarters: "Woodbury, MN",
    commonDisputes: ["gym-cancellation", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Anytime Fitness Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Anytime Fitness franchises have individual contracts — read your specific agreement",
      "Many states have gym membership cancellation rights — check your state law",
      "Send cancellation notice via certified mail and keep the receipt",
      "File a BBB complaint if the franchise continues billing after cancellation",
    ],
  },
  {
    name: "Gold's Gym",
    slug: "golds-gym",
    industry: "Fitness & Services",
    headquarters: "Dallas, TX",
    commonDisputes: ["gym-cancellation", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Gold's Gym Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Gold's Gym locations are often franchises — contact the specific location for cancellation",
      "Check your state's health club membership laws for cancellation rights",
      "Send cancellation via certified mail for documentation",
      "File a State AG complaint for billing after valid cancellation",
    ],
  },
  {
    name: "Equinox",
    slug: "equinox",
    industry: "Fitness & Services",
    headquarters: "New York, NY",
    commonDisputes: ["gym-cancellation", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Equinox Member Services"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Equinox memberships are expensive and often have complex cancellation terms",
      "Review your membership agreement for the cancellation notice period",
      "Equinox typically requires 45 days notice to cancel — plan ahead",
      "File a State AG complaint if Equinox refuses to honor a valid cancellation",
    ],
  },
  {
    name: "24 Hour Fitness",
    slug: "24-hour-fitness",
    industry: "Fitness & Services",
    headquarters: "San Ramon, CA",
    commonDisputes: ["gym-cancellation", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "24 Hour Fitness Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "24 Hour Fitness went through bankruptcy — verify your membership status and terms",
      "Send cancellation requests via certified mail for proof of delivery",
      "Check your state's health club membership laws for cancellation and refund rights",
      "File a BBB or State AG complaint if billing continues after cancellation",
    ],
  },
  {
    name: "ADT",
    slug: "adt",
    industry: "Fitness & Services",
    headquarters: "Boca Raton, FL",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "ADT Customer Care"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Hard",
    tips: [
      "ADT contracts typically have early termination fees — review your agreement",
      "You may have a 3-day right of rescission after signing — act immediately",
      "Send cancellation by certified mail to the address in your contract",
      "File a State AG complaint for deceptive sales practices or unauthorized charges",
    ],
  },
  {
    name: "Vivint",
    slug: "vivint",
    industry: "Fitness & Services",
    headquarters: "Lehi, UT",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Vivint Customer Support"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Hard",
    tips: [
      "Vivint contracts are typically 42-60 months — review early termination fees",
      "You may have a 3-day right of rescission after signing — act immediately",
      "Vivint has faced multiple AG actions for aggressive sales tactics — cite these",
      "File a State AG complaint for misleading sales or unauthorized installations",
    ],
  },
  {
    name: "Terminix",
    slug: "terminix",
    industry: "Fitness & Services",
    headquarters: "Memphis, TN",
    commonDisputes: ["subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB", "EPA"],
    complaintChannels: ["BBB", "FTC", "State AG", "Terminix Customer Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Terminix guarantees are typically for a specific period — check your contract",
      "Request a re-treatment if pests return within the guarantee period",
      "File a State AG complaint for ineffective treatment or unauthorized charges",
      "Document any property damage caused by treatment with photos and video",
    ],
  },

  // ─── Rental & Moving ─────────────────────────────────────────────────────────
  {
    name: "Enterprise Rent-A-Car",
    slug: "enterprise-rent-a-car",
    industry: "Rental & Moving",
    headquarters: "St. Louis, MO",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "insurance-denial"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Enterprise Customer Service"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Take photos of the rental car before and after — dispute any damage claims with evidence",
      "Decline the damage waiver only if your personal insurance or credit card covers rentals",
      "Enterprise must provide a damage claim with specific repair estimates",
      "File a State AG complaint for fraudulent damage charges",
    ],
  },
  {
    name: "Hertz",
    slug: "hertz",
    industry: "Rental & Moving",
    headquarters: "Estero, FL",
    commonDisputes: ["chargeback-dispute", "general-demand-letter", "insurance-denial"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Hertz Customer Relations"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Hertz has faced lawsuits for false theft reports against renters — document your return",
      "Take detailed photos of the vehicle at pickup and return",
      "Request a copy of the damage assessment if charged for damage",
      "File a State AG complaint for fraudulent damage or theft claims",
    ],
  },
  {
    name: "Avis / Budget",
    slug: "avis-budget",
    industry: "Rental & Moving",
    headquarters: "Parsippany, NJ",
    commonDisputes: ["chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB"],
    complaintChannels: ["BBB", "FTC", "State AG", "Avis/Budget Customer Service"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Take photos of the rental at pickup and return — focus on existing damage",
      "Check your credit card for rental car coverage before purchasing the waiver",
      "Request a detailed invoice breakdown if additional charges appear",
      "File a credit card chargeback for unauthorized charges",
    ],
  },
  {
    name: "U-Haul",
    slug: "u-haul",
    industry: "Rental & Moving",
    headquarters: "Phoenix, AZ",
    commonDisputes: ["moving-damage-claim", "chargeback-dispute", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB", "FMCSA"],
    complaintChannels: ["BBB", "FTC", "State AG", "U-Haul Customer Action Line"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "U-Haul's $50 reservation guarantee applies if they cannot fulfill your reservation",
      "Document the truck's condition before departure with photos and video",
      "U-Haul charges are based on mileage and fuel — verify both at return",
      "File a State AG complaint for unauthorized charges or unreturned deposits",
    ],
  },
  {
    name: "PODS",
    slug: "pods",
    industry: "Rental & Moving",
    headquarters: "Clearwater, FL",
    commonDisputes: ["moving-damage-claim", "subscription-refund", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB", "FMCSA"],
    complaintChannels: ["BBB", "FTC", "State AG", "PODS Customer Care"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "PODS charges monthly storage fees — monitor your billing carefully",
      "Take detailed photos of items before loading the container",
      "PODS damage claims must be filed promptly — check your agreement for deadlines",
      "Request a written quote and confirm all fees before booking",
    ],
  },
  {
    name: "Two Men and a Truck",
    slug: "two-men-and-a-truck",
    industry: "Rental & Moving",
    headquarters: "Lansing, MI",
    commonDisputes: ["moving-damage-claim", "general-demand-letter"],
    regulatoryBodies: ["FTC", "State Attorney General", "BBB", "FMCSA"],
    complaintChannels: ["BBB", "FTC", "State AG", "FMCSA", "Two Men and a Truck Corporate"],
    estimatedResolutionTime: "2-4 weeks",
    difficultyLevel: "Medium",
    tips: [
      "Two Men and a Truck is a franchise — direct complaints to both the franchise and corporate",
      "File a damage claim in writing within the timeframe specified in your moving agreement",
      "Take photos of all items before the move, especially fragile or valuable pieces",
      "Request a copy of the Bill of Lading — it is your contract with the mover",
    ],
  },
];

export function getCompanyBySlug(slug: string): CompanyInfo | undefined {
  return COMPANIES.find((c) => c.slug === slug);
}

export function getAllCompanySlugs(): string[] {
  return COMPANIES.map((c) => c.slug);
}

export function getCompaniesByIndustry(industry: string): CompanyInfo[] {
  return COMPANIES.filter((c) => c.industry === industry);
}
