// ---------------------------------------------------------------------------
// states.ts -- All 50 states + DC: small claims data, consumer protections
// ---------------------------------------------------------------------------

export interface StateInfo {
  name: string;
  abbreviation: string;
  slug: string;
  smallClaimsLimit: number;
  filingFeeRange: string;
  statuteOfLimitations: string;
  keyStatutes: string[];
  courtName: string;
  lawyersAllowed: boolean;
  corporatePlaintiffs: boolean;
  onlineFilingAvailable: boolean;
  keyConsumerProtections: string[];
  capitalCity: string;
  population: string;
}

export const STATES: StateInfo[] = [
  {
    name: "Alabama",
    abbreviation: "AL",
    slug: "alabama",
    smallClaimsLimit: 6000,
    filingFeeRange: "$25-$50",
    statuteOfLimitations: "6 years (written), 6 years (oral)",
    keyStatutes: ["Ala. Code § 35-9A-201", "Ala. Code § 8-19-1 (Deceptive Trade Practices)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Deceptive Trade Practices Act", "Landlord-Tenant Act", "Lemon Law (Ala. Code § 8-20A-1)"],
    capitalCity: "Montgomery",
    population: "5.1M",
  },
  {
    name: "Alaska",
    abbreviation: "AK",
    slug: "alaska",
    smallClaimsLimit: 10000,
    filingFeeRange: "$30-$75",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["Alaska Stat. § 34.03.070", "Alaska Stat. § 45.50.471 (Unfair Trade Practices)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair Trade Practices Act", "Landlord-Tenant Act 14-day deposit return", "Lemon Law"],
    capitalCity: "Juneau",
    population: "733K",
  },
  {
    name: "Arizona",
    abbreviation: "AZ",
    slug: "arizona",
    smallClaimsLimit: 3500,
    filingFeeRange: "$15-$50",
    statuteOfLimitations: "3 years (oral), 6 years (written)",
    keyStatutes: ["Ariz. Rev. Stat. § 33-1321", "Ariz. Rev. Stat. § 44-1521 (Consumer Fraud Act)"],
    courtName: "Justice Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Fraud Act", "Residential Landlord-Tenant Act", "Lemon Law", "Security Deposit 14-day return"],
    capitalCity: "Phoenix",
    population: "7.4M",
  },
  {
    name: "Arkansas",
    abbreviation: "AR",
    slug: "arkansas",
    smallClaimsLimit: 5000,
    filingFeeRange: "$30-$65",
    statuteOfLimitations: "5 years (oral), 5 years (written)",
    keyStatutes: ["Ark. Code § 18-16-305", "Ark. Code § 4-88-101 (Deceptive Trade Practices)"],
    courtName: "District Court - Small Claims Division",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Deceptive Trade Practices Act", "Security Deposit Act", "Lemon Law (Ark. Code § 4-90-401)"],
    capitalCity: "Little Rock",
    population: "3.0M",
  },
  {
    name: "California",
    abbreviation: "CA",
    slug: "california",
    smallClaimsLimit: 12500,
    filingFeeRange: "$30-$75",
    statuteOfLimitations: "2 years (oral), 4 years (written)",
    keyStatutes: ["Cal. Civ. Code § 1950.5", "Song-Beverly Consumer Warranty Act", "Cal. Civ. Code § 1770 (CLRA)"],
    courtName: "Superior Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Lemon Law (Song-Beverly Act)", "Security Deposit 21-day return", "CLRA consumer rights", "Prop 65 disclosures", "CCPA data privacy"],
    capitalCity: "Sacramento",
    population: "39.5M",
  },
  {
    name: "Colorado",
    abbreviation: "CO",
    slug: "colorado",
    smallClaimsLimit: 7500,
    filingFeeRange: "$31-$55",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Colo. Rev. Stat. § 38-12-103", "Colo. Rev. Stat. § 6-1-101 (Consumer Protection Act)"],
    courtName: "County Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Protection Act", "Security Deposit 60-day return (3x damages)", "Lemon Law", "Warranty of Habitability"],
    capitalCity: "Denver",
    population: "5.8M",
  },
  {
    name: "Connecticut",
    abbreviation: "CT",
    slug: "connecticut",
    smallClaimsLimit: 5000,
    filingFeeRange: "$30-$60",
    statuteOfLimitations: "3 years (oral), 6 years (written)",
    keyStatutes: ["Conn. Gen. Stat. § 47a-21", "Conn. Gen. Stat. § 42-110a (CUTPA)"],
    courtName: "Superior Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["CUTPA (Unfair Trade Practices)", "Security Deposit 30-day return (2x damages)", "Lemon Law", "Home Improvement Act"],
    capitalCity: "Hartford",
    population: "3.6M",
  },
  {
    name: "Delaware",
    abbreviation: "DE",
    slug: "delaware",
    smallClaimsLimit: 25000,
    filingFeeRange: "$35-$50",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["Del. Code tit. 25 § 5514", "Del. Code tit. 6 § 2511 (Consumer Fraud Act)"],
    courtName: "Justice of the Peace Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Fraud Act", "Landlord-Tenant Code", "Lemon Law", "Security Deposit 20-day return"],
    capitalCity: "Dover",
    population: "1.0M",
  },
  {
    name: "District of Columbia",
    abbreviation: "DC",
    slug: "district-of-columbia",
    smallClaimsLimit: 10000,
    filingFeeRange: "$5-$45",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["D.C. Code § 42-3502", "D.C. Code § 28-3901 (Consumer Protection Procedures Act)"],
    courtName: "Superior Court - Small Claims and Conciliation Branch",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Protection Procedures Act", "Tenant Bill of Rights", "Security Deposit 45-day return", "Rent Control protections"],
    capitalCity: "Washington",
    population: "689K",
  },
  {
    name: "Florida",
    abbreviation: "FL",
    slug: "florida",
    smallClaimsLimit: 8000,
    filingFeeRange: "$55-$300",
    statuteOfLimitations: "4 years (oral), 5 years (written)",
    keyStatutes: ["Fla. Stat. § 83.49", "Fla. Stat. § 501.201 (Deceptive and Unfair Trade Practices Act)"],
    courtName: "County Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["FDUTPA consumer protection", "Security Deposit 15-30 day return", "Lemon Law (Fla. Stat. § 681)", "Condo/HOA regulations"],
    capitalCity: "Tallahassee",
    population: "22.2M",
  },
  {
    name: "Georgia",
    abbreviation: "GA",
    slug: "georgia",
    smallClaimsLimit: 15000,
    filingFeeRange: "$45-$75",
    statuteOfLimitations: "4 years (oral), 6 years (written)",
    keyStatutes: ["Ga. Code § 44-7-30", "Ga. Code § 10-1-390 (Fair Business Practices Act)"],
    courtName: "Magistrate Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Fair Business Practices Act", "Landlord-Tenant Act", "Lemon Law (Ga. Code § 10-1-780)", "Security Deposit 30-day return"],
    capitalCity: "Atlanta",
    population: "10.9M",
  },
  {
    name: "Hawaii",
    abbreviation: "HI",
    slug: "hawaii",
    smallClaimsLimit: 5000,
    filingFeeRange: "$15-$35",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Haw. Rev. Stat. § 521-44", "Haw. Rev. Stat. § 480-2 (Unfair and Deceptive Acts)"],
    courtName: "District Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair and Deceptive Acts or Practices", "Landlord-Tenant Code", "Security Deposit 14-day return", "Lemon Law"],
    capitalCity: "Honolulu",
    population: "1.4M",
  },
  {
    name: "Idaho",
    abbreviation: "ID",
    slug: "idaho",
    smallClaimsLimit: 5000,
    filingFeeRange: "$20-$69",
    statuteOfLimitations: "4 years (oral), 5 years (written)",
    keyStatutes: ["Idaho Code § 6-321", "Idaho Code § 48-601 (Consumer Protection Act)"],
    courtName: "Magistrate Division - Small Claims",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Security Deposit 21-30 day return", "Lemon Law", "Idaho Consumer Credit Code"],
    capitalCity: "Boise",
    population: "1.9M",
  },
  {
    name: "Illinois",
    abbreviation: "IL",
    slug: "illinois",
    smallClaimsLimit: 10000,
    filingFeeRange: "$20-$175",
    statuteOfLimitations: "5 years (oral), 10 years (written)",
    keyStatutes: ["765 ILCS 710 (Security Deposit Return Act)", "815 ILCS 505 (Consumer Fraud Act)"],
    courtName: "Circuit Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Fraud and Deceptive Business Practices Act", "Security Deposit Return Act", "Lemon Law", "Chicago RLTO (Chicago tenants)"],
    capitalCity: "Springfield",
    population: "12.5M",
  },
  {
    name: "Indiana",
    abbreviation: "IN",
    slug: "indiana",
    smallClaimsLimit: 10000,
    filingFeeRange: "$20-$85",
    statuteOfLimitations: "6 years (oral), 10 years (written)",
    keyStatutes: ["Ind. Code § 32-31-3", "Ind. Code § 24-5-0.5 (Deceptive Consumer Sales Act)"],
    courtName: "Small Claims Court of Marion County / Township Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Deceptive Consumer Sales Act", "Security Deposit Act 45-day return", "Lemon Law", "Home Improvement Contract Act"],
    capitalCity: "Indianapolis",
    population: "6.8M",
  },
  {
    name: "Iowa",
    abbreviation: "IA",
    slug: "iowa",
    smallClaimsLimit: 6500,
    filingFeeRange: "$20-$100",
    statuteOfLimitations: "5 years (oral), 10 years (written)",
    keyStatutes: ["Iowa Code § 562A.12", "Iowa Code § 714H (Consumer Fraud Act)"],
    courtName: "Small Claims Court (District Court Division)",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Fraud Act", "Security Deposit 30-day return", "Lemon Law", "Landlord-Tenant Act"],
    capitalCity: "Des Moines",
    population: "3.2M",
  },
  {
    name: "Kansas",
    abbreviation: "KS",
    slug: "kansas",
    smallClaimsLimit: 4000,
    filingFeeRange: "$25-$65",
    statuteOfLimitations: "3 years (oral), 5 years (written)",
    keyStatutes: ["Kan. Stat. § 58-2550", "Kan. Stat. § 50-623 (Consumer Protection Act)"],
    courtName: "District Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Residential Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Topeka",
    population: "2.9M",
  },
  {
    name: "Kentucky",
    abbreviation: "KY",
    slug: "kentucky",
    smallClaimsLimit: 2500,
    filingFeeRange: "$20-$50",
    statuteOfLimitations: "5 years (oral), 15 years (written)",
    keyStatutes: ["Ky. Rev. Stat. § 383.580", "Ky. Rev. Stat. § 367.110 (Consumer Protection Act)"],
    courtName: "District Court - Small Claims Division",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 30-60 day return", "Lemon Law"],
    capitalCity: "Frankfort",
    population: "4.5M",
  },
  {
    name: "Louisiana",
    abbreviation: "LA",
    slug: "louisiana",
    smallClaimsLimit: 5000,
    filingFeeRange: "$25-$80",
    statuteOfLimitations: "10 years (oral), 10 years (written)",
    keyStatutes: ["La. R.S. 9:3251", "La. R.S. 51:1401 (Unfair Trade Practices Act)"],
    courtName: "City Court / Justice of the Peace - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair Trade Practices and Consumer Protection Law", "Security Deposit Act 30-day return", "Lemon Law (La. R.S. 51:1941)", "Redhibition (product defect rights)"],
    capitalCity: "Baton Rouge",
    population: "4.6M",
  },
  {
    name: "Maine",
    abbreviation: "ME",
    slug: "maine",
    smallClaimsLimit: 6000,
    filingFeeRange: "$30-$80",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Me. Rev. Stat. tit. 14 § 6031", "Me. Rev. Stat. tit. 5 § 205-A (Unfair Trade Practices)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair Trade Practices Act", "Security Deposit Act 30-day return", "Lemon Law", "Warranty of Habitability"],
    capitalCity: "Augusta",
    population: "1.4M",
  },
  {
    name: "Maryland",
    abbreviation: "MD",
    slug: "maryland",
    smallClaimsLimit: 5000,
    filingFeeRange: "$15-$45",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["Md. Code Real Prop. § 8-203", "Md. Code Com. Law § 13-101 (Consumer Protection Act)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Protection Act", "Security Deposit 45-day return", "Lemon Law", "Landlord-Tenant escrow rights"],
    capitalCity: "Annapolis",
    population: "6.2M",
  },
  {
    name: "Massachusetts",
    abbreviation: "MA",
    slug: "massachusetts",
    smallClaimsLimit: 7000,
    filingFeeRange: "$30-$60",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Mass. Gen. Laws ch. 186 § 15B", "Mass. Gen. Laws ch. 93A (Consumer Protection)"],
    courtName: "Boston Municipal Court / District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Chapter 93A consumer protection (treble damages)", "Security Deposit 30-day return (3x damages)", "Lemon Law", "Warranty of Habitability"],
    capitalCity: "Boston",
    population: "7.0M",
  },
  {
    name: "Michigan",
    abbreviation: "MI",
    slug: "michigan",
    smallClaimsLimit: 6500,
    filingFeeRange: "$30-$70",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Mich. Comp. Laws § 554.602", "Mich. Comp. Laws § 445.901 (Consumer Protection Act)"],
    courtName: "District Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Security Deposit Act 30-day return", "Lemon Law", "Truth in Renting Act"],
    capitalCity: "Lansing",
    population: "10.0M",
  },
  {
    name: "Minnesota",
    abbreviation: "MN",
    slug: "minnesota",
    smallClaimsLimit: 15000,
    filingFeeRange: "$30-$75",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Minn. Stat. § 504B.178", "Minn. Stat. § 325D.44 (Prevention of Consumer Fraud Act)"],
    courtName: "District Court - Conciliation Court",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Prevention of Consumer Fraud Act", "Security Deposit 21-day return (2x damages)", "Lemon Law", "Tenant Remedies Act"],
    capitalCity: "Saint Paul",
    population: "5.7M",
  },
  {
    name: "Mississippi",
    abbreviation: "MS",
    slug: "mississippi",
    smallClaimsLimit: 3500,
    filingFeeRange: "$25-$50",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["Miss. Code § 89-8-1", "Miss. Code § 75-24-1 (Consumer Protection Act)"],
    courtName: "Justice Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 45-day return", "Lemon Law"],
    capitalCity: "Jackson",
    population: "2.9M",
  },
  {
    name: "Missouri",
    abbreviation: "MO",
    slug: "missouri",
    smallClaimsLimit: 5000,
    filingFeeRange: "$20-$60",
    statuteOfLimitations: "5 years (oral), 10 years (written)",
    keyStatutes: ["Mo. Rev. Stat. § 535.300", "Mo. Rev. Stat. § 407.010 (Merchandising Practices Act)"],
    courtName: "Circuit Court - Small Claims Division",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Merchandising Practices Act", "Landlord-Tenant Law", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Jefferson City",
    population: "6.2M",
  },
  {
    name: "Montana",
    abbreviation: "MT",
    slug: "montana",
    smallClaimsLimit: 7000,
    filingFeeRange: "$10-$30",
    statuteOfLimitations: "5 years (oral), 8 years (written)",
    keyStatutes: ["Mont. Code § 70-25-201", "Mont. Code § 30-14-101 (Unfair Trade Practices)"],
    courtName: "Justice Court / City Court - Small Claims",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair Trade Practices Act", "Security Deposit 10-30 day return", "Lemon Law", "Landlord-Tenant Act"],
    capitalCity: "Helena",
    population: "1.1M",
  },
  {
    name: "Nebraska",
    abbreviation: "NE",
    slug: "nebraska",
    smallClaimsLimit: 3600,
    filingFeeRange: "$15-$57",
    statuteOfLimitations: "4 years (oral), 5 years (written)",
    keyStatutes: ["Neb. Rev. Stat. § 76-1416", "Neb. Rev. Stat. § 59-1601 (Consumer Protection Act)"],
    courtName: "County Court - Small Claims",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Security Deposit 14-day return", "Lemon Law", "Uniform Residential Landlord-Tenant Act"],
    capitalCity: "Lincoln",
    population: "2.0M",
  },
  {
    name: "Nevada",
    abbreviation: "NV",
    slug: "nevada",
    smallClaimsLimit: 10000,
    filingFeeRange: "$36-$100",
    statuteOfLimitations: "4 years (oral), 6 years (written)",
    keyStatutes: ["Nev. Rev. Stat. § 118A.242", "Nev. Rev. Stat. § 598.0903 (Deceptive Trade Practices)"],
    courtName: "Justice Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Deceptive Trade Practices Act", "Security Deposit 30-day return", "Lemon Law", "Landlord-Tenant Act"],
    capitalCity: "Carson City",
    population: "3.2M",
  },
  {
    name: "New Hampshire",
    abbreviation: "NH",
    slug: "new-hampshire",
    smallClaimsLimit: 10000,
    filingFeeRange: "$45-$125",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["N.H. Rev. Stat. § 540-A:7", "N.H. Rev. Stat. § 358-A (Consumer Protection Act)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Security Deposit 30-day return", "Lemon Law", "Landlord-Tenant regulations"],
    capitalCity: "Concord",
    population: "1.4M",
  },
  {
    name: "New Jersey",
    abbreviation: "NJ",
    slug: "new-jersey",
    smallClaimsLimit: 5000,
    filingFeeRange: "$15-$50",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["N.J. Stat. § 46:8-19", "N.J. Stat. § 56:8-1 (Consumer Fraud Act)"],
    courtName: "Superior Court - Special Civil Part - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Fraud Act (treble damages)", "Security Deposit Act 30-day return", "Lemon Law", "Truth in Consumer Contract Act"],
    capitalCity: "Trenton",
    population: "9.3M",
  },
  {
    name: "New Mexico",
    abbreviation: "NM",
    slug: "new-mexico",
    smallClaimsLimit: 10000,
    filingFeeRange: "$25-$55",
    statuteOfLimitations: "4 years (oral), 6 years (written)",
    keyStatutes: ["N.M. Stat. § 47-8-18", "N.M. Stat. § 57-12-1 (Unfair Practices Act)"],
    courtName: "Metropolitan Court / Magistrate Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair Practices Act", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Santa Fe",
    population: "2.1M",
  },
  {
    name: "New York",
    abbreviation: "NY",
    slug: "new-york",
    smallClaimsLimit: 10000,
    filingFeeRange: "$10-$30",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["N.Y. Gen. Oblig. Law § 7-108", "N.Y. Gen. Bus. Law § 349 (Consumer Protection)"],
    courtName: "City Court / District Court / Justice Court - Small Claims Part",
    lawyersAllowed: true,
    corporatePlaintiffs: false,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["GBL § 349 deceptive practices", "Security Deposit 14-day return", "Lemon Law (strong)", "Rent stabilization (NYC)", "Warranty of Habitability"],
    capitalCity: "Albany",
    population: "19.6M",
  },
  {
    name: "North Carolina",
    abbreviation: "NC",
    slug: "north-carolina",
    smallClaimsLimit: 10000,
    filingFeeRange: "$30-$96",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["N.C. Gen. Stat. § 42-50", "N.C. Gen. Stat. § 75-1.1 (Unfair and Deceptive Trade Practices)"],
    courtName: "District Court - Small Claims Division (Magistrate Court)",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair and Deceptive Trade Practices Act (treble damages)", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Raleigh",
    population: "10.7M",
  },
  {
    name: "North Dakota",
    abbreviation: "ND",
    slug: "north-dakota",
    smallClaimsLimit: 15000,
    filingFeeRange: "$10-$50",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["N.D. Cent. Code § 47-16-07.1", "N.D. Cent. Code § 51-15-01 (Consumer Fraud)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Fraud Act", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Bismarck",
    population: "780K",
  },
  {
    name: "Ohio",
    abbreviation: "OH",
    slug: "ohio",
    smallClaimsLimit: 6000,
    filingFeeRange: "$20-$60",
    statuteOfLimitations: "6 years (oral), 8 years (written)",
    keyStatutes: ["Ohio Rev. Code § 5321.16", "Ohio Rev. Code § 1345.01 (Consumer Sales Practices Act)"],
    courtName: "Municipal Court / County Court - Small Claims Division",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Sales Practices Act", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Columbus",
    population: "11.8M",
  },
  {
    name: "Oklahoma",
    abbreviation: "OK",
    slug: "oklahoma",
    smallClaimsLimit: 10000,
    filingFeeRange: "$30-$90",
    statuteOfLimitations: "3 years (oral), 5 years (written)",
    keyStatutes: ["Okla. Stat. tit. 41 § 115", "Okla. Stat. tit. 15 § 751 (Consumer Protection Act)"],
    courtName: "District Court - Small Claims Division",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 45-day return", "Lemon Law"],
    capitalCity: "Oklahoma City",
    population: "4.0M",
  },
  {
    name: "Oregon",
    abbreviation: "OR",
    slug: "oregon",
    smallClaimsLimit: 10000,
    filingFeeRange: "$35-$55",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Or. Rev. Stat. § 90.300", "Or. Rev. Stat. § 646.605 (Unlawful Trade Practices Act)"],
    courtName: "Circuit Court / Justice Court - Small Claims Department",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Unlawful Trade Practices Act", "Security Deposit 31-day return", "Lemon Law", "Residential Landlord-Tenant Act"],
    capitalCity: "Salem",
    population: "4.2M",
  },
  {
    name: "Pennsylvania",
    abbreviation: "PA",
    slug: "pennsylvania",
    smallClaimsLimit: 12000,
    filingFeeRange: "$35-$100",
    statuteOfLimitations: "4 years (oral), 4 years (written)",
    keyStatutes: ["68 Pa. Stat. § 250.511a", "73 Pa. Stat. § 201-1 (Unfair Trade Practices and Consumer Protection Law)"],
    courtName: "Magisterial District Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Unfair Trade Practices and Consumer Protection Law", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law", "Plain Language Consumer Contract Act"],
    capitalCity: "Harrisburg",
    population: "13.0M",
  },
  {
    name: "Rhode Island",
    abbreviation: "RI",
    slug: "rhode-island",
    smallClaimsLimit: 5000,
    filingFeeRange: "$15-$30",
    statuteOfLimitations: "10 years (oral), 10 years (written)",
    keyStatutes: ["R.I. Gen. Laws § 34-18-19", "R.I. Gen. Laws § 6-13.1-1 (Deceptive Trade Practices)"],
    courtName: "District Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Deceptive Trade Practices Act", "Landlord-Tenant Act", "Security Deposit 20-day return", "Lemon Law"],
    capitalCity: "Providence",
    population: "1.1M",
  },
  {
    name: "South Carolina",
    abbreviation: "SC",
    slug: "south-carolina",
    smallClaimsLimit: 7500,
    filingFeeRange: "$25-$80",
    statuteOfLimitations: "3 years (oral), 3 years (written)",
    keyStatutes: ["S.C. Code § 27-40-410", "S.C. Code § 39-5-10 (Unfair Trade Practices Act)"],
    courtName: "Magistrate Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Unfair Trade Practices Act", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Columbia",
    population: "5.2M",
  },
  {
    name: "South Dakota",
    abbreviation: "SD",
    slug: "south-dakota",
    smallClaimsLimit: 12000,
    filingFeeRange: "$25-$50",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["S.D. Codified Laws § 43-32-6.1", "S.D. Codified Laws § 37-24-1 (Deceptive Trade Practices)"],
    courtName: "Circuit Court - Small Claims Procedure",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Deceptive Trade Practices Act", "Landlord-Tenant Act", "Security Deposit 14-day return (2x damages)", "Lemon Law"],
    capitalCity: "Pierre",
    population: "910K",
  },
  {
    name: "Tennessee",
    abbreviation: "TN",
    slug: "tennessee",
    smallClaimsLimit: 25000,
    filingFeeRange: "$25-$75",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Tenn. Code § 66-28-301", "Tenn. Code § 47-18-101 (Consumer Protection Act)"],
    courtName: "General Sessions Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Nashville",
    population: "7.1M",
  },
  {
    name: "Texas",
    abbreviation: "TX",
    slug: "texas",
    smallClaimsLimit: 20000,
    filingFeeRange: "$30-$100",
    statuteOfLimitations: "4 years (oral), 4 years (written)",
    keyStatutes: ["Tex. Prop. Code § 92.101", "Tex. Bus. & Com. Code § 17.41 (DTPA)"],
    courtName: "Justice Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Deceptive Trade Practices Act (DTPA - treble damages)", "Security Deposit 30-day return", "Lemon Law (Tex. Occ. Code Ch. 2301)", "Landlord-Tenant repairs"],
    capitalCity: "Austin",
    population: "30.5M",
  },
  {
    name: "Utah",
    abbreviation: "UT",
    slug: "utah",
    smallClaimsLimit: 11000,
    filingFeeRange: "$35-$75",
    statuteOfLimitations: "4 years (oral), 6 years (written)",
    keyStatutes: ["Utah Code § 57-17-1", "Utah Code § 13-11-1 (Consumer Sales Practices Act)"],
    courtName: "Justice Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Sales Practices Act", "Landlord-Tenant Act", "Security Deposit 30-day return", "Lemon Law"],
    capitalCity: "Salt Lake City",
    population: "3.4M",
  },
  {
    name: "Vermont",
    abbreviation: "VT",
    slug: "vermont",
    smallClaimsLimit: 5000,
    filingFeeRange: "$30-$75",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Vt. Stat. tit. 9 § 4461", "Vt. Stat. tit. 9 § 2451 (Consumer Protection Act)"],
    courtName: "Superior Court - Small Claims Procedure",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 14-day return", "Lemon Law"],
    capitalCity: "Montpelier",
    population: "647K",
  },
  {
    name: "Virginia",
    abbreviation: "VA",
    slug: "virginia",
    smallClaimsLimit: 5000,
    filingFeeRange: "$30-$65",
    statuteOfLimitations: "3 years (oral), 5 years (written)",
    keyStatutes: ["Va. Code § 55.1-1226", "Va. Code § 59.1-196 (Consumer Protection Act)"],
    courtName: "General District Court - Small Claims Division",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 45-day return", "Lemon Law"],
    capitalCity: "Richmond",
    population: "8.6M",
  },
  {
    name: "Washington",
    abbreviation: "WA",
    slug: "washington",
    smallClaimsLimit: 10000,
    filingFeeRange: "$20-$75",
    statuteOfLimitations: "3 years (oral), 6 years (written)",
    keyStatutes: ["Wash. Rev. Code § 59.18.280", "Wash. Rev. Code § 19.86.010 (Consumer Protection Act)"],
    courtName: "District Court - Small Claims Department",
    lawyersAllowed: false,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Consumer Protection Act (treble damages)", "Security Deposit 21-day return (2x damages)", "Lemon Law", "Landlord-Tenant Act"],
    capitalCity: "Olympia",
    population: "7.7M",
  },
  {
    name: "West Virginia",
    abbreviation: "WV",
    slug: "west-virginia",
    smallClaimsLimit: 10000,
    filingFeeRange: "$15-$50",
    statuteOfLimitations: "5 years (oral), 10 years (written)",
    keyStatutes: ["W. Va. Code § 37-6A-1", "W. Va. Code § 46A-6-101 (Consumer Credit and Protection Act)"],
    courtName: "Magistrate Court",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Credit and Protection Act", "Landlord-Tenant Act", "Security Deposit 60-day return", "Lemon Law"],
    capitalCity: "Charleston",
    population: "1.8M",
  },
  {
    name: "Wisconsin",
    abbreviation: "WI",
    slug: "wisconsin",
    smallClaimsLimit: 10000,
    filingFeeRange: "$30-$95",
    statuteOfLimitations: "6 years (oral), 6 years (written)",
    keyStatutes: ["Wis. Stat. § 704.28", "Wis. Stat. § 100.18 (Fraudulent Representations)"],
    courtName: "Circuit Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: true,
    keyConsumerProtections: ["Fraudulent Representations Act", "Landlord-Tenant ATCP 134 rules", "Security Deposit 21-day return", "Lemon Law"],
    capitalCity: "Madison",
    population: "5.9M",
  },
  {
    name: "Wyoming",
    abbreviation: "WY",
    slug: "wyoming",
    smallClaimsLimit: 6000,
    filingFeeRange: "$10-$30",
    statuteOfLimitations: "8 years (oral), 10 years (written)",
    keyStatutes: ["Wyo. Stat. § 1-21-1201", "Wyo. Stat. § 40-12-101 (Consumer Protection Act)"],
    courtName: "Circuit Court - Small Claims",
    lawyersAllowed: true,
    corporatePlaintiffs: true,
    onlineFilingAvailable: false,
    keyConsumerProtections: ["Consumer Protection Act", "Landlord-Tenant Act", "Security Deposit 30-day return (refundable only)", "Lemon Law"],
    capitalCity: "Cheyenne",
    population: "577K",
  },
];

export function getStateBySlug(slug: string): StateInfo | undefined {
  return STATES.find((s) => s.slug === slug);
}

export function getAllStateSlugs(): string[] {
  return STATES.map((s) => s.slug);
}
