import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: August 2026</p>
      <div className="prose prose-slate mt-8 dark:prose-invert max-w-none space-y-4 text-sm leading-relaxed text-slate-600 dark:text-slate-400">
        <p>
          AI Dispute Engine (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is
          a self-help software platform that generates document templates for
          consumer disputes. We are <strong>not a law firm</strong> and do not
          provide legal advice, representation, or counsel.
        </p>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">
          Use of Service
        </h2>
        <p>
          Documents generated by AI Dispute Engine are informational templates
          based on publicly available legal information. They are not a
          substitute for legal advice from a licensed attorney. You are
          responsible for reviewing, editing, and using any documents generated
          through our platform.
        </p>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">
          Payments and Refunds
        </h2>
        <p>
          Payments are processed securely through Stripe. Your first letter is
          free. Subsequent letters are charged at the per-letter or subscription
          rate displayed at the time of purchase. Subscriptions can be cancelled
          at any time from your account settings.
        </p>
        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">
          Limitation of Liability
        </h2>
        <p>
          AI Dispute Engine is provided &quot;as is&quot; without warranty of
          any kind. We are not liable for any outcomes resulting from the use of
          documents generated through our platform.
        </p>
      </div>
    </div>
  );
}
