import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Demand Letter Translation — AI Dispute Engine",
  description:
    "Professional translation of your demand letter to Spanish, Chinese, Korean, Vietnamese, or Tagalog. Legal terminology accuracy with cultural context adaptation. Only $5.",
};

const CHECK = (
  <svg className="mt-0.5 h-4 w-4 shrink-0 text-teal-600 dark:text-teal-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
  </svg>
);

const ARROW = (
  <svg className="ml-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
  </svg>
);

const STEPS = [
  {
    step: 1,
    title: "Upload or Paste Your Letter",
    description:
      "Upload your demand letter as a file or paste the text directly. Works with any demand letter — including those generated by AI Dispute Engine.",
  },
  {
    step: 2,
    title: "Choose Your Language",
    description:
      "Select from Spanish, Chinese (Simplified), Korean, Vietnamese, or Tagalog. Each translation is adapted for legal accuracy and cultural context.",
  },
  {
    step: 3,
    title: "Download Your Translation",
    description:
      "Download a professionally translated letter with the original and translated versions side by side. Ready to send to the recipient.",
  },
];

const INCLUDED = [
  "Professional legal translation with terminology accuracy",
  "Cultural context adaptation so the letter lands with full impact",
  "Legal terminology preserved with correct equivalent terms",
  "Original and translated versions side by side in one PDF",
  "Certified translation statement included",
  "5 language options: Spanish, Chinese, Korean, Vietnamese, and Tagalog",
  "PDF & DOCX download ready to send",
];

const FAQ = [
  {
    q: "Why translate my demand letter?",
    a: "If the recipient of your demand letter primarily speaks a language other than English, sending the letter in their language dramatically increases the chances they will read, understand, and respond to it. A translated letter also demonstrates professionalism and seriousness — showing you invested in clear communication rather than assuming they would figure it out on their own.",
  },
  {
    q: "Is this a certified translation?",
    a: "Each translation includes a certified translation statement — a declaration that the translation is a true and accurate rendering of the original document. This statement is accepted by most businesses, agencies, and courts for non-immigration purposes. For court filings that require a sworn translator affidavit, you may need to have the translation reviewed by a certified human translator in your jurisdiction.",
  },
  {
    q: "What languages are available?",
    a: "We currently offer translations in the five most commonly spoken non-English languages in the United States: Spanish, Chinese (Simplified), Korean, Vietnamese, and Tagalog. These five languages cover over 75% of limited-English-proficiency households in the U.S. Additional languages may be added in the future.",
  },
  {
    q: "Can I translate other legal documents?",
    a: "This tool is optimized for demand letters and legal correspondence. The translation engine understands legal terminology, formal tone, and the structure of demand letters specifically. For other types of legal documents — such as contracts, court filings, or affidavits — the translation will still work, but we recommend having a human translator review documents intended for court submission.",
  },
];

export default function LetterTranslationPage() {
  return (
    <div className="bg-white dark:bg-slate-950">
      {/* Breadcrumb */}
      <div className="mx-auto max-w-6xl px-4 pt-8 sm:px-6">
        <nav className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
          <Link href="/" className="hover:text-teal-600 dark:hover:text-teal-400">Home</Link>
          <span>/</span>
          <Link href="/disputes" className="hover:text-teal-600 dark:hover:text-teal-400">Tools</Link>
          <span>/</span>
          <span className="text-slate-900 dark:text-white">Demand Letter Translation</span>
        </nav>
      </div>

      {/* Hero */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="mx-auto max-w-3xl text-center">
          <p className="mb-4 inline-block rounded-full border border-teal-500/30 bg-teal-500/10 px-4 py-1.5 text-sm font-medium text-teal-600 dark:text-teal-400">
            $5 per translation
          </p>
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Your Demand. Their Language. Full Impact.</h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-slate-600 dark:text-slate-400">
            Professionally translate your demand letter to Spanish, Chinese, Korean, Vietnamese, or Tagalog. Accurate legal terminology with cultural context adaptation so your letter hits with full force.
          </p>
          <div className="mt-8">
            <Link href="/disputes" className="inline-flex items-center justify-center rounded-lg bg-teal-600 px-6 py-3.5 text-base font-semibold text-white transition hover:bg-teal-500">
              Translate Your Letter — $5{ARROW}
            </Link>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="border-y border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900/50">
        <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
          <h2 className="text-center text-2xl font-bold sm:text-3xl">How it works</h2>
          <div className="mt-12 grid gap-8 sm:grid-cols-3">
            {STEPS.map((s) => (
              <div key={s.step} className="text-center">
                <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-teal-600 text-xl font-bold text-white">{s.step}</div>
                <h3 className="mt-4 text-sm font-bold">{s.title}</h3>
                <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{s.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What's Included */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="mx-auto max-w-3xl">
          <h2 className="text-center text-2xl font-bold sm:text-3xl">What&apos;s included</h2>
          <ul className="mx-auto mt-10 max-w-xl space-y-4">
            {INCLUDED.map((item) => (
              <li key={item} className="flex gap-3 text-sm text-slate-700 dark:text-slate-300">{CHECK} {item}</li>
            ))}
          </ul>
        </div>
      </section>

      {/* CTA Banner */}
      <section className="mx-auto max-w-6xl px-4 pb-8 sm:px-6">
        <div className="rounded-2xl bg-slate-950 p-8 text-center text-white sm:p-12 dark:border dark:border-slate-700 dark:bg-slate-900">
          <h2 className="text-2xl font-bold sm:text-3xl">Make Sure Your Message Gets Through</h2>
          <p className="mx-auto mt-4 max-w-xl text-slate-300">A demand letter only works if the recipient can read it. For $5, ensure your legal communication lands with full clarity and impact — in the language they understand best.</p>
          <div className="mt-8">
            <Link href="/disputes" className="inline-flex items-center justify-center rounded-lg bg-teal-600 px-6 py-3.5 text-base font-semibold text-white transition hover:bg-teal-500">
              Translate Your Letter — $5{ARROW}
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-20">
        <h2 className="text-center text-2xl font-bold">Common questions</h2>
        <div className="mt-8 divide-y divide-slate-200 dark:divide-slate-800">
          {FAQ.map((item) => (
            <div key={item.q} className="py-5">
              <h3 className="text-sm font-semibold">{item.q}</h3>
              <p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-400">{item.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* JSON-LD */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{
        __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "Product",
          name: "Demand Letter Translation",
          description: "Professional translation of your demand letter to Spanish, Chinese, Korean, Vietnamese, or Tagalog. Legal terminology accuracy with cultural context adaptation.",
          brand: { "@type": "Brand", name: "AI Dispute Engine" },
          offers: { "@type": "Offer", price: "5.00", priceCurrency: "USD", priceValidUntil: "2027-12-31", availability: "https://schema.org/InStock", url: "https://aidisputeengine.com/tools/letter-translation" },
        }),
      }} />

      {/* Disclaimer */}
      <section className="border-t border-slate-200 dark:border-slate-800">
        <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
          <p className="text-xs leading-relaxed text-slate-400 dark:text-slate-500">
            Disclaimer: AI Dispute Engine is not a law firm and does not provide legal advice. The documents generated by this service are for informational purposes only and do not constitute legal advice. For legal advice specific to your situation, consult a licensed attorney in your jurisdiction.
          </p>
        </div>
      </section>
    </div>
  );
}
